### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by urraka** [opensoldat/manual#1]
- [ ] Open [this](https://urraka.github.io/soldat-manual/manual.html#options-join) image similarly to how it's done in https://soldat.pl/en/screenshots/

- [ ] Highlight sidebar items on mouse hover

    ![hover-red](https://user-images.githubusercontent.com/2616266/40075456-b61dafce-5852-11e8-9589-7aa00f1121e8.png)
    ![hover-dark](https://user-images.githubusercontent.com/2616266/40075455-b5fa2b08-5852-11e8-8004-0b580f899393.png)

- [x] Choose proper colors and use this for keys

    ```css
    kbd {
        background-color: #3c8e37;
        border: 1px solid #0d3c0b;
        border-radius: 2px;
        box-shadow: 0 1px 0 rgb(60, 142, 55),0 0 0 2px #3c8e37 inset;
        color: #d9f3d8;
        display: inline-block;
        font-size: 14px;
        margin: 0 .1em;
        padding: 0.1em .4em;
        text-shadow: 0 1px 0 #000;
    }
    ```
    ![kbd](https://user-images.githubusercontent.com/2616266/40075054-b75ddc52-5851-11e8-855b-fefa796a216f.png)

- [ ] Consider suggestions from https://forums.soldat.pl/index.php?topic=45164.msg531530#msg531530

- [ ] Turn sidebar into mobile friendly menu on mobile devices
